#!/usr/bin/env python3
"""
Custom Feature Validation Script for VANGA LSTM

This script validates CSV files for custom features and provides
recommendations for feature engineering and model training.
"""

import pandas as pd
import numpy as np
import argparse
import sys
from pathlib import Path

def validate_csv_structure(df):
    """Validate basic CSV structure and required columns."""
    required_cols = ['timestamp', 'open', 'high', 'low', 'close', 'volume']
    missing_cols = [col for col in required_cols if col not in df.columns]

    if missing_cols:
        return False, f"Missing required columns: {missing_cols}"

    return True, "Basic structure valid"

def analyze_custom_features(df):
    """Analyze custom features and provide recommendations."""
    required_cols = ['timestamp', 'open', 'high', 'low', 'close', 'volume']
    custom_cols = [col for col in df.columns if col not in required_cols]

    if not custom_cols:
        return {
            'status': 'no_custom_features',
            'message': 'No custom features detected - only OHLCV data',
            'recommendations': ['Consider adding sentiment, on-chain, or macro indicators']
        }

    analysis = {
        'status': 'custom_features_found',
        'custom_features': custom_cols,
        'feature_count': len(custom_cols),
        'recommendations': [],
        'transformations': {},
        'warnings': []
    }

    for col in custom_cols:
        series = df[col]

        # Check for missing values
        missing_pct = series.isnull().sum() / len(series) * 100
        if missing_pct > 10:
            analysis['warnings'].append(f"{col}: {missing_pct:.1f}% missing values")

        # Analyze distribution and recommend transformations
        if series.dtype in ['int64', 'float64']:
            skewness = series.skew()

            # Recommend transformations based on data characteristics
            if abs(skewness) > 2:
                if series.min() > 0:
                    analysis['transformations'][col] = 'Log'
                    analysis['recommendations'].append(f"{col}: Highly skewed, recommend Log transformation")
                else:
                    analysis['transformations'][col] = 'RobustScale'
                    analysis['recommendations'].append(f"{col}: Highly skewed with negatives, recommend RobustScale")
            elif 'sentiment' in col.lower() or 'ratio' in col.lower():
                analysis['transformations'][col] = 'ZScore'
                analysis['recommendations'].append(f"{col}: Recommend ZScore normalization")
            elif 'rate' in col.lower() or 'change' in col.lower():
                analysis['transformations'][col] = 'PercentChange'
                analysis['recommendations'].append(f"{col}: Recommend PercentChange transformation")
            elif series.min() >= 0 and series.max() <= 100:
                analysis['transformations'][col] = 'MinMaxScale'
                analysis['recommendations'].append(f"{col}: Bounded values, recommend MinMaxScale")
            elif 'volume' in col.lower() or 'count' in col.lower() or 'address' in col.lower():
                analysis['transformations'][col] = 'Log'
                analysis['recommendations'].append(f"{col}: Volume/count data, recommend Log transformation")

    return analysis

def generate_config_template(analysis, output_path):
    """Generate a TOML configuration template based on the analysis."""
    template = """# Auto-generated configuration for custom features
# Generated by VANGA feature validation script

[technical_indicators]
enabled = true

[technical_indicators.moving_averages]
sma_periods = [5, 10, 20, 50]
ema_periods = [5, 10, 20, 50]

[technical_indicators.momentum]
rsi_periods = [14, 21]
stochastic = true

[technical_indicators.volatility]
bollinger_bands = { enabled = true, period = 20, std_dev = 2.0 }
atr_periods = [14]

[market_microstructure]
enabled = true

[market_microstructure.price_dynamics]
velocity_periods = [5, 10, 20]

[volatility_features]
enabled = true

[volatility_features.realized_volatility]
periods = ["1h", "4h", "24h"]

[custom_features]
auto_include_all = true

"""

    if analysis.get('transformations'):
        template += "# Recommended transformations based on data analysis\n"
        template += "[custom_features.transformations]\n"
        for feature, transform in analysis['transformations'].items():
            template += f'{feature} = "{transform}"\n'
        template += "\n"

    template += """[engineering]
[engineering.lag_features]
enabled = true
lag_periods = [1, 2, 3, 5]
features_to_lag = ["close", "volume"]

[engineering.rolling_features]
enabled = true
window_sizes = [5, 10, 20]
statistics = ["Mean", "Std"]

[selection]
enabled = true
max_features = 80
correlation_threshold = 0.95
importance_threshold = 0.001
"""

    with open(output_path, 'w') as f:
        f.write(template)

def main():
    parser = argparse.ArgumentParser(description='Validate CSV for VANGA LSTM custom features')
    parser.add_argument('csv_file', help='Path to CSV file to validate')
    parser.add_argument('--generate-config', help='Generate TOML config file', metavar='OUTPUT_PATH')
    parser.add_argument('--verbose', '-v', action='store_true', help='Verbose output')

    args = parser.parse_args()

    # Load and validate CSV
    try:
        df = pd.read_csv(args.csv_file)
        print(f"✅ Successfully loaded CSV: {len(df)} rows, {len(df.columns)} columns")
    except Exception as e:
        print(f"❌ Error loading CSV: {e}")
        sys.exit(1)

    # Validate structure
    valid, message = validate_csv_structure(df)
    if not valid:
        print(f"❌ Structure validation failed: {message}")
        sys.exit(1)
    else:
        print(f"✅ {message}")

    # Analyze custom features
    analysis = analyze_custom_features(df)

    if analysis['status'] == 'no_custom_features':
        print(f"ℹ️  {analysis['message']}")
        for rec in analysis['recommendations']:
            print(f"💡 {rec}")
    else:
        print(f"✅ Found {analysis['feature_count']} custom features:")
        for feature in analysis['custom_features']:
            print(f"   - {feature}")

        if analysis['warnings']:
            print("\n⚠️  Warnings:")
            for warning in analysis['warnings']:
                print(f"   - {warning}")

        if analysis['recommendations']:
            print("\n💡 Recommendations:")
            for rec in analysis['recommendations']:
                print(f"   - {rec}")

    # Generate config if requested
    if args.generate_config:
        generate_config_template(analysis, args.generate_config)
        print(f"\n📝 Generated configuration template: {args.generate_config}")
        print("   Edit the template as needed and use with:")
        print(f"   vanga train --symbol SYMBOL --data {args.csv_file} --features-config {args.generate_config}")

    # Verbose output
    if args.verbose and analysis.get('transformations'):
        print("\n🔧 Recommended transformations:")
        for feature, transform in analysis['transformations'].items():
            print(f"   {feature}: {transform}")

if __name__ == '__main__':
    main()
